# Docker Compose for Scaled/Load-Balanced Setup
# Multiple PHP containers with APCu caching (container-isolated)
#
# USAGE:
# 1. Using defaults:
#    docker compose -f docker-compose.scale.yml up -d --scale phpweave=3
#
# 2. Using host environment variables:
#    export DB_PASSWORD=my_secure_password
#    docker compose -f docker-compose.scale.yml up -d --scale phpweave=3
#
# 3. Using .env.docker file:
#    source .env.docker
#    docker compose -f docker-compose.scale.yml up -d --scale phpweave=3
#
# Note: APCu cache is isolated per container, so each instance has its own cache

services:
  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: phpweave-lb
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - phpweave-1
      - phpweave-2
      - phpweave-3
    restart: unless-stopped
    networks:
      - phpweave-network

  # PHP Application Instance 1
  phpweave-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpweave-app-1
    environment:
      # Docker environment
      - DOCKER_ENV=${DOCKER_ENV:-production}
      - PHPWEAVE_ENV=${PHPWEAVE_ENV:-production}
      - INSTANCE_ID=1

      # Database configuration (using DB_* naming convention)
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-phpweave}
      - DB_USER=${DB_USER:-phpweave_user}
      - DB_PASSWORD=${DB_PASSWORD:-phpweave_pass}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DRIVER=${DB_DRIVER:-pdo_mysql}
      - DB_DSN=${DB_DSN:-}

      # Application settings
      - DEBUG=${DEBUG:-0}
    restart: unless-stopped
    networks:
      - phpweave-network
    depends_on:
      - db

  # PHP Application Instance 2
  phpweave-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpweave-app-2
    environment:
      # Docker environment
      - DOCKER_ENV=${DOCKER_ENV:-production}
      - PHPWEAVE_ENV=${PHPWEAVE_ENV:-production}
      - INSTANCE_ID=2

      # Database configuration (using DB_* naming convention)
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-phpweave}
      - DB_USER=${DB_USER:-phpweave_user}
      - DB_PASSWORD=${DB_PASSWORD:-phpweave_pass}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DRIVER=${DB_DRIVER:-pdo_mysql}
      - DB_DSN=${DB_DSN:-}

      # Application settings
      - DEBUG=${DEBUG:-0}
    restart: unless-stopped
    networks:
      - phpweave-network
    depends_on:
      - db

  # PHP Application Instance 3
  phpweave-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpweave-app-3
    environment:
      # Docker environment
      - DOCKER_ENV=${DOCKER_ENV:-production}
      - PHPWEAVE_ENV=${PHPWEAVE_ENV:-production}
      - INSTANCE_ID=3

      # Database configuration (using DB_* naming convention)
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-phpweave}
      - DB_USER=${DB_USER:-phpweave_user}
      - DB_PASSWORD=${DB_PASSWORD:-phpweave_pass}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DRIVER=${DB_DRIVER:-pdo_mysql}
      - DB_DSN=${DB_DSN:-}

      # Application settings
      - DEBUG=${DEBUG:-0}
    restart: unless-stopped
    networks:
      - phpweave-network
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: phpweave-db-scaled
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-phpweave}
      MYSQL_USER: ${DB_USER:-phpweave_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-phpweave_pass}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - phpweave-network

volumes:
  db-data:
    driver: local

networks:
  phpweave-network:
    driver: bridge
