apiVersion: v1
kind: ConfigMap
metadata:
  name: phpweave-config
data:
  DEBUG: "0"
  APP_ENV: "production"
  DBHOST: "mysql-service"
  DBNAME: "phpweave"
  DBCHARSET: "utf8mb4"
  CACHE_ENABLED: "1"
  APCU_ENABLED: "1"
  ERROR_REPORTING: "E_ALL & ~E_NOTICE"
  TIMEZONE: "UTC"