apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phpweave-metrics
  labels:
    app: phpweave
    app.kubernetes.io/name: phpweave
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: kustomize
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: phpweave
      app.kubernetes.io/name: phpweave
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
  namespaceSelector:
    matchNames:
    - phpweave
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-metrics
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: kustomize
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: mysql
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
  namespaceSelector:
    matchNames:
    - phpweave
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-metrics-service
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app: mysql
    app.kubernetes.io/name: mysql
  ports:
  - name: metrics
    port: 9104
    targetPort: 9104
    protocol: TCP